/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.FilmDatabase;
import model.MyFilmDatabase;

/**
 *
 * @author Farley Tran
 */
public class AddFilmDialog extends javax.swing.JDialog
{

    /**
     * Creates new form AddFilmDialog
     */
    public AddFilmDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        favoriteCheckBox = new javax.swing.JCheckBox();
        filmNameLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        trailerLinkTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        image3Btn = new javax.swing.JButton();
        image1Label = new javax.swing.JLabel();
        filmNameTextField = new javax.swing.JTextField();
        image3Label = new javax.swing.JLabel();
        backgroundBtn = new javax.swing.JButton();
        descriptionLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        image2Btn = new javax.swing.JButton();
        image2Label = new javax.swing.JLabel();
        trailerLinkLabel = new javax.swing.JLabel();
        blurayCheckBox = new javax.swing.JCheckBox();
        episodesTextField = new javax.swing.JTextField();
        episodesLabel = new javax.swing.JLabel();
        movieLocLabel = new javax.swing.JLabel();
        image1Btn = new javax.swing.JButton();
        movieLocBtn = new javax.swing.JButton();
        seasonCombox = new javax.swing.JComboBox<>();
        seasonLabel = new javax.swing.JLabel();
        image3Sample = new javax.swing.JLabel();
        image1Sample = new javax.swing.JLabel();
        image2Sample = new javax.swing.JLabel();
        image4Sample = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 0));

        favoriteCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        favoriteCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        favoriteCheckBox.setText("Favorite");

        filmNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        filmNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        filmNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        filmNameLabel.setText("Name");

        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Background");

        image3Btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                image3BtnActionPerformed(evt);
            }
        });

        image1Label.setBackground(new java.awt.Color(0, 0, 0));
        image1Label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        image1Label.setForeground(new java.awt.Color(255, 255, 255));
        image1Label.setText("Image1");

        image3Label.setBackground(new java.awt.Color(0, 0, 0));
        image3Label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        image3Label.setForeground(new java.awt.Color(255, 255, 255));
        image3Label.setText("Image3");

        backgroundBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backgroundBtnActionPerformed(evt);
            }
        });

        descriptionLabel.setBackground(new java.awt.Color(0, 0, 0));
        descriptionLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("Description");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelBtnActionPerformed(evt);
            }
        });

        image2Btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                image2BtnActionPerformed(evt);
            }
        });

        image2Label.setBackground(new java.awt.Color(0, 0, 0));
        image2Label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        image2Label.setForeground(new java.awt.Color(255, 255, 255));
        image2Label.setText("Image2");

        trailerLinkLabel.setBackground(new java.awt.Color(0, 0, 0));
        trailerLinkLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        trailerLinkLabel.setForeground(new java.awt.Color(255, 255, 255));
        trailerLinkLabel.setText("Trailer link");

        blurayCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        blurayCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        blurayCheckBox.setText("Blu-ray");

        episodesLabel.setBackground(new java.awt.Color(0, 0, 0));
        episodesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        episodesLabel.setForeground(new java.awt.Color(255, 255, 255));
        episodesLabel.setText("Episodes");

        movieLocLabel.setBackground(new java.awt.Color(0, 0, 0));
        movieLocLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        movieLocLabel.setForeground(new java.awt.Color(255, 255, 255));
        movieLocLabel.setText("Movie Location");

        image1Btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                image1BtnActionPerformed(evt);
            }
        });

        movieLocBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                movieLocBtnActionPerformed(evt);
            }
        });

        seasonCombox.setBackground(new java.awt.Color(0, 0, 0));
        seasonCombox.setForeground(new java.awt.Color(255, 255, 255));
        seasonCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        seasonLabel.setBackground(new java.awt.Color(0, 0, 0));
        seasonLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        seasonLabel.setForeground(new java.awt.Color(255, 255, 255));
        seasonLabel.setText("Season:");

        image3Sample.setBackground(new java.awt.Color(255, 255, 255));
        image3Sample.setIcon(getImageIcon(image3Btn.getText(),270,400));
        image3Sample.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        image1Sample.setBackground(new java.awt.Color(255, 255, 255));
        image1Sample.setForeground(new java.awt.Color(255, 255, 255));
        image1Sample.setIcon(getImageIcon(image1Btn.getText(),270,400));
        image1Sample.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        image2Sample.setBackground(new java.awt.Color(255, 255, 255));
        image2Sample.setIcon(getImageIcon(image2Btn.getText(),270,400));
        image2Sample.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        image4Sample.setBackground(new java.awt.Color(255, 255, 255));
        image4Sample.setForeground(new java.awt.Color(255, 255, 255));
        image4Sample.setIcon(getImageIcon(backgroundBtn.getText(),270,400));
        image4Sample.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        jDesktopPane1.setLayer(favoriteCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filmNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(okBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(trailerLinkTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image3Btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image1Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filmNameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image3Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(backgroundBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(descriptionLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cancelBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image2Btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image2Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(trailerLinkLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(blurayCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(episodesTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(episodesLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(movieLocLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image1Btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(movieLocBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(seasonCombox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(seasonLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image3Sample, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image1Sample, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image2Sample, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(image4Sample, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(image3Label)
                        .addGap(87, 87, 87)
                        .addComponent(image3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(image2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(image1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(favoriteCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(okBtn)
                                    .addComponent(cancelBtn))
                                .addGap(31, 31, 31)))
                        .addGap(18, 18, 18)
                        .addComponent(blurayCheckBox))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backgroundBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(seasonCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movieLocLabel)
                            .addComponent(episodesLabel)
                            .addComponent(trailerLinkLabel)
                            .addComponent(filmNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(trailerLinkTextField)
                            .addComponent(episodesTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(movieLocBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(filmNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(seasonLabel)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(image1Sample, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image2Sample, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(image3Sample, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(image4Sample, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, okBtn});

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backgroundBtn, episodesTextField, image1Btn, image2Btn, image3Btn, movieLocBtn});

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {image1Sample, image2Sample, image3Sample});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filmNameLabel)
                            .addComponent(filmNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trailerLinkLabel)
                            .addComponent(trailerLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(episodesLabel)
                            .addComponent(episodesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movieLocLabel)
                            .addComponent(movieLocBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(image1Label)
                            .addComponent(image1Btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(image2Label)
                            .addComponent(image2Btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(image3Label)
                            .addComponent(image3Btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(favoriteCheckBox)
                            .addComponent(blurayCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seasonLabel)
                            .addComponent(seasonCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(descriptionLabel)
                                .addGap(74, 74, 74)
                                .addComponent(okBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn)
                                .addContainerGap())
                            .addComponent(jScrollPane1)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image2Sample, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image3Sample, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image1Sample, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(image4Sample, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelBtn, okBtn});

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backgroundBtn, image1Btn, image2Btn, image3Btn, movieLocBtn});

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {image1Sample, image2Sample, image3Sample});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okBtnActionPerformed
    {//GEN-HEADEREND:event_okBtnActionPerformed
        String name = filmNameTextField.getText();
        String movieLocation = movieLocBtn.getText();
        boolean favorite = favoriteCheckBox.isSelected();
        boolean bluray = blurayCheckBox.isSelected();
        String trailerLink = trailerLinkTextField.getText();
        String description = descriptionTextArea.getText();
        String image1 = image1Btn.getText();
        String image2 = image2Btn.getText();
        String image3 = image3Btn.getText();
        int season = seasonCombox.getSelectedIndex();
        String episodes = episodesTextField.getText();
        String background = backgroundBtn.getText();
        if(movieLocation == "")
        {
            JOptionPane.showMessageDialog(this, "Can not find movie location", "Error!",JOptionPane.ERROR_MESSAGE);
        } else
        {
        FilmDatabase fd = new FilmDatabase
        (name, movieLocation, favorite, 
                bluray, trailerLink, description, 
                image1, image2, image3, 
                season, episodes, background);
        filmInfo.getFilmInfo(fd);
        
        }
        this.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelBtnActionPerformed
    {//GEN-HEADEREND:event_cancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void movieLocBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_movieLocBtnActionPerformed
    {//GEN-HEADEREND:event_movieLocBtnActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.showOpenDialog(jfc);
        String moviePath = jfc.getSelectedFile().toString();
        moviePath = moviePath.replace('\\', '/') + "/";
        HashMap<Integer,FilmDatabase> list = myFilmDatabase.getListFilm();
        boolean isExist = false;
        for(int i : list.keySet())
        {
            if(i == -1)
            {
                continue;
            }
            if(list.get(i).getMovieLocation().equals(moviePath))
            {
                JOptionPane.showMessageDialog(jfc, "Movie already exists!", "Please choose another movie!",
                        JOptionPane.INFORMATION_MESSAGE);
                isExist = true;
                break;
            }
        }
        if(!isExist)
        {
            movieLocBtn.setText(moviePath);
        }
    }//GEN-LAST:event_movieLocBtnActionPerformed

    private ImageIcon getImageIcon(String path, int widthImg,
            int heightImg)
    {
        ImageIcon dabIcon = new ImageIcon(path);
        Image dabImage = dabIcon.getImage();
        Image modDabImage = dabImage.getScaledInstance(widthImg,
                heightImg, widthImg);
        return new ImageIcon(modDabImage);
    }
    private void image1BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_image1BtnActionPerformed
    {//GEN-HEADEREND:event_image1BtnActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new ImageFileFilter());
        jfc.showOpenDialog(jfc);
        String image = jfc.getSelectedFile().toString();
        image = image.replace('\\', '/');
        image1Btn.setText(image);
        image1Sample.setIcon(getImageIcon(image1Btn.getText(),468,578));
    }//GEN-LAST:event_image1BtnActionPerformed

    private void image2BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_image2BtnActionPerformed
    {//GEN-HEADEREND:event_image2BtnActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new ImageFileFilter());
        jfc.showOpenDialog(jfc);
        String image = jfc.getSelectedFile().toString();
        image = image.replace('\\', '/');
        image2Btn.setText(image);
        image2Sample.setIcon(getImageIcon(image2Btn.getText(),468,578));
    }//GEN-LAST:event_image2BtnActionPerformed

    private void image3BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_image3BtnActionPerformed
    {//GEN-HEADEREND:event_image3BtnActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new ImageFileFilter());
        jfc.showOpenDialog(jfc);
        String image = jfc.getSelectedFile().toString();
        image = image.replace('\\', '/');
        image3Btn.setText(image);
        image3Sample.setIcon(getImageIcon(image3Btn.getText(),468,578));
    }//GEN-LAST:event_image3BtnActionPerformed

    private void backgroundBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backgroundBtnActionPerformed
    {//GEN-HEADEREND:event_backgroundBtnActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new ImageFileFilter());
        jfc.showOpenDialog(jfc);
        String image = jfc.getSelectedFile().toString();
        image = image.replace('\\', '/');
        backgroundBtn.setText(image);
        image4Sample.setIcon(getImageIcon(backgroundBtn.getText(),1428,478));
    }//GEN-LAST:event_backgroundBtnActionPerformed
    public void setFilmInfo(FilmInfo filmInfo)
    {
        this.filmInfo = filmInfo;
    }
    public void setMyFilmDatabase(MyFilmDatabase myFilmDatabase)
    {
        this.myFilmDatabase = myFilmDatabase;
    }
    private FilmInfo filmInfo;
    private MyFilmDatabase myFilmDatabase;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backgroundBtn;
    private javax.swing.JCheckBox blurayCheckBox;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel episodesLabel;
    private javax.swing.JTextField episodesTextField;
    private javax.swing.JCheckBox favoriteCheckBox;
    private javax.swing.JLabel filmNameLabel;
    private javax.swing.JTextField filmNameTextField;
    private javax.swing.JButton image1Btn;
    private javax.swing.JLabel image1Label;
    private javax.swing.JLabel image1Sample;
    private javax.swing.JButton image2Btn;
    private javax.swing.JLabel image2Label;
    private javax.swing.JLabel image2Sample;
    private javax.swing.JButton image3Btn;
    private javax.swing.JLabel image3Label;
    private javax.swing.JLabel image3Sample;
    private javax.swing.JLabel image4Sample;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton movieLocBtn;
    private javax.swing.JLabel movieLocLabel;
    private javax.swing.JButton okBtn;
    private javax.swing.JComboBox<String> seasonCombox;
    private javax.swing.JLabel seasonLabel;
    private javax.swing.JLabel trailerLinkLabel;
    private javax.swing.JTextField trailerLinkTextField;
    // End of variables declaration//GEN-END:variables
}
