/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import model.FilmDatabase;
import model.MyFilmDatabase;

/**
 *
 * @author Farley Tran
 */
public class FilmPanel extends javax.swing.JPanel
{

    /**
     * Creates new form FilmPanel
     */
    public FilmPanel(FilmDatabase fd, MyFilmDatabase mfd)
    {
        this.filmDatabase = fd;
        this.myFilmDatabase = mfd;
        initComponents(); 
        filmName.setText(filmDatabase.getName());
    }
    public FilmPanel()
    {
        filmDatabase = new FilmDatabase(null,null, false, 
        true, null, 
        null, null , null, null, 0, null, null);
        initComponents(); 
    }
    public void getFilm()
    {
        this.clickedBtn.setEnabled(true);
    }

    private ImageIcon getImageIcon(String path, int widthImg,
            int heightImg)
    {
        if(path == null)
        {
            path = "src/data/filmDatabase/umaru1.png";
        }
        ImageIcon dabIcon = new ImageIcon(path);
        Image dabImage = dabIcon.getImage();
        Image modDabImage = dabImage.getScaledInstance(widthImg,
                heightImg, widthImg);
        return new ImageIcon(modDabImage);
    }
    public void setLinkLayer(LinkLayer link)
    {
        this.link = link;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        filmImage = new javax.swing.JLabel();
        filmName = new javax.swing.JLabel();
        blurayIcon = new javax.swing.JLabel();
        clickedBtn = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        filmImage.setIcon(getImageIcon(filmDatabase.getImage1(),250,350));
        jDesktopPane2.add(filmImage);
        filmImage.setBounds(0, 0, 250, 350);

        filmName.setBackground(new java.awt.Color(102, 102, 102));
        filmName.setForeground(new java.awt.Color(255, 255, 255));
        filmName.setOpaque(true);
        jDesktopPane2.add(filmName);
        filmName.setBounds(0, 350, 250, 50);

        blurayIcon.setIcon(getImageIcon("src/data/filmImage/blu-ray.png",240,150));
        blurayIcon.setVisible(filmDatabase.isBluray());
        jDesktopPane2.setLayer(blurayIcon, javax.swing.JLayeredPane.PALETTE_LAYER);
        jDesktopPane2.add(blurayIcon);
        blurayIcon.setBounds(0, 250, 240, 150);

        clickedBtn.setText("clickedBtn");
        clickedBtn.setEnabled(false);
        if(filmDatabase.getMovieLocation() != null)
        {
            clickedBtn.setEnabled(true);
        }
        clickedBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clickedBtnActionPerformed(evt);
            }
        });
        jDesktopPane2.add(clickedBtn);
        clickedBtn.setBounds(0, 0, 250, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void removeFilmInfo(Component cpnt)
    {
        this.remove(cpnt);
    }
    public int getFilmID()
    {
        return filmDatabase.getFilmID();
    }
    private void clickedBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clickedBtnActionPerformed
    {//GEN-HEADEREND:event_clickedBtnActionPerformed
        FilmInfoPanel filmInfo = new FilmInfoPanel(filmDatabase,myFilmDatabase);
        filmInfo.setLinkLayer(link);
        filmInfo.setVisible(true);
        if(link != null)
        {
            link.setHomeVisiable(false);
        }
    }//GEN-LAST:event_clickedBtnActionPerformed
    
    private MyFilmDatabase myFilmDatabase;
    private FilmDatabase filmDatabase;
    private LinkLayer link = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blurayIcon;
    private javax.swing.JButton clickedBtn;
    public javax.swing.JLabel filmImage;
    private javax.swing.JLabel filmName;
    private javax.swing.JDesktopPane jDesktopPane2;
    // End of variables declaration//GEN-END:variables
}
