version: "3.9"
services:
  faceswap:
    image: namphuongtran9196/3dface
    container_name: 3dface
    volumes:
      - ./inputs:/code/inputs
      - ./outputs:/code/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]